const storyLines = [
    { branch: 1, card: 1, text: `"Overwatch, this is Viper.  Going comms dark for final approach.  Over."  You are Marcone, the Viper.  The Kinammon Empire and their whelps have killed everyone you love, and enslaved your world.  Now is the time to go on the offensive.  You have used up all of your political and military capital, burned all of your deep-cover allies for this one shot to take down their flagship, “The Killmonger”, sending a burning message of resistance across the cosmos.  There is no going back.  Choose your approach:`
         },
    { branch: 1, card: 2, text: `In your younger years, you may have gone with a more measured approach, but these vermin deserve to suffer.  You resume course towards their operations hangar and ready all weapons.  “Time to burn”, you whisper into the void.  As you close to within 300 meters, you upload your computer virus to the Killmonger’s mainframe while simultaneously unleashing the full payload of the weapons cache you spent months cobbling together.  Billions of dollars of credits spent in seconds.  But as the shields begin to flicker, and then collapse, you realize it was money well spent.  You gun the engines, land in the middle of the debris, and prepare for war.  
    The Kinamite guards on duty that weren’t sucked out into space have begun to collect themselves.  One or two even take pot shots at your craft, as if their rifles could pierce your ship’s armor.  You give yourself one last systems check, powering on your armor and loading weapons.  You have room in your thigh holster for one more piece of gear.  But what to choose?` 
        },
    { branch: 1, card: 3, text: `You eject out of your cockpit in a sudden explosion of pressure, using your boot-thrusters to come crashing into the middle of the guards, your mass and speed turning surprised Kinamites to mist.  As the rest come to after the shock of your sudden and vicious onslaught, you shoot two Kinamites in the head as you leap forward and front kick a third so hard, he goes flying 20 meters, before hitting the wing of another craft and careening off in two distinct pieces.  With the last of the guards dispatched, you race into the hall, and note the distinct lack of alarms.  Seems your computer virus was worth the hefty price tag.  You come to a fork in the hallway.  Which way do you go?` 
        },
    { branch: 1, card: 4, text: `You arrive outside the ship’s core, having met little resistance on the way.  Enemies and innocents have both fallen to your blade this day, but you can spare little in the way of empathy right now.  You have a mission to complete.  There are two soldiers at the far end of the warehouse sized Vault, who have noticed you and raised weapons.  No time to think!  React!` 
        },
    { branch: 1, card: 5.1, text: `You activate your thrusters, cover your semi-exposed face with your heavily armored forearms and fly straight at them, holding your blade like a javelin.  You accelerated too fast however, and after feeling one Kinamite simply explode upon impact with your armored body, you fly straight into the wall at Mach-1.  Gross.`
        },
    { branch: 1, card: 5.2, text: `You raise your carbine, the aiming reticle already synced to your helmet’s HUD.  You manage to get one shot off before one of the enemy’s armor-piercing rounds penetrates your armor and goes right through the meat of your left thigh.  The armor clamps the wounds shut, but you are perceptively slowed nonetheless.  As the next enemy round rips your carbine out of your hands, you reflexively draw the ion sword on your back, and throw it like a javelin.  Your aim is true and the sword tip cuts through the Kinamites chest armor like paper and spears him to the wall.`
       },
    { branch: 1, card: 5.3, text: `Before the enemy has a chance to react, you raise your wrist launcher and fire a stun grenade at them, launching yourself after it, not waiting for it to detonate.  The grenade detonates, rendering the Kinamites temporarily deaf and blind, while your helmet saves you from the worst of it.  The Kinamites fire blindly, one round getting lucky and passes through your thigh, eliciting a grunt of pain in response.  But now you’re among them.  And they are no more.`
        },
];

const endings = [
    { branch: 1, rating: "excellent", text: `You approach the ship’s core and stare into the heart of the Killmonger, the most feared warship of it’s age.  As you rip off the fusion pack from the low back of your armor, and prime it to go nuclear, you calculate the odds of you making it back to your ship before it detonates.  You exit the now powerless armor, strap your makeshift bomb to the nexis of the ship, and run back to the hangar as fast as your wound will alow.  The fleet is in chaos, this ship no exception.  Alarm Klaxons are wailing now, and you meet little resistance as death and destruction reigns supreme outside.  Your ship, sensing your presence, begins to power up as you near and takes off the second you hit the seat.  You pat the ship in fondness as you peel away at maximum burn, the explosion of the Killmonger resembling a supernova in the reflection of your helmet’s visor.  Mission accomplished.`
        },
    { branch: 1, rating: "poor", text: `The wound in your thigh steadily burns as your armor tries, and fails, to staunch the wound.  The projectile damn near ripped off your leg, the high-tech armor the only thing keeping the limb remotely useful.  You always knew this might be a one-way trip, your thigh wound reinforcing that idea.  You say a silent prayer to your loved ones, as you begin to prime your fusion pack to go nuclear.  As you reach to input the final activation code, you feel a wet thud as an enemy spear pierces your torso from behind.  You fall to your knees as a Kinamite stands before you.  You failed, and the Kinammon Empire will continue un-checked.  Gleaming red eyes are the last things you see`
        },
    { branch: 1, rating: "neutral", text: `You have precious few seconds to complete your mission before you’re overwhelmed.  You wasted most of your armor’s energy reserves making it to the core.  You know you’ll never make it back to your ship in one piece.  And while you were hoping you wouldn’t have to use this, it seems you’re out of options.  You prime the fusion pack on your lower back to go nuclear.  You exhale a breath as you accept your fate and repeat your favorite mantra, “Once more unto the breach dear fr…”, as a flash of white lights up the world and the Killmonger is no more.` 
        },
];